# Bear Market Optimized Volume Profile Strategy
# Focus: Improved performance in bear/sideways markets
# Addressing: Poor bear market Sharpe ratio and minimal returns

version: "2.0"
name: "Bear Market Optimized VP Strategy"
symbol: "BTC/USDT"
exchange: "binanceus"

timeframes:
  entry: "15m"
  analysis: "1h"
  regime: "1d"  # Daily timeframe for major regime detection

indicators:
  # Volume Profile optimized for ranging/bear markets
  - id: "VP_Bear"
    type: "VolumeProfile"
    timeframe: "15m"
    lookback: 288         # 3 days (shorter for more reactive levels)
    price_bins: 100       # Higher resolution for precise levels
    value_area_pct: 68    # Tighter value area for better signals
    update_frequency: 2   # More frequent updates
    min_volume_threshold: 0.2
    atr_period: 14
    atr_multiplier: 1.0   # Tighter breakout requirements
  
  # Market regime detection
  - id: "ADX_Daily"
    type: "ADX"
    timeframe: "1d"
    period: 14
    trend_threshold: 25
    range_threshold: 20
  
  # Multiple EMA regime filter
  - id: "EMA_Fast"
    type: "EMA"
    timeframe: "1h"
    length: 12
  
  - id: "EMA_Medium"
    type: "EMA"
    timeframe: "1h"  
    length: 26
  
  - id: "EMA_Slow"
    type: "EMA"
    timeframe: "4h"
    length: 50
  
  # Volatility filter
  - id: "ATR_Vol"
    type: "RSI"  # Using RSI as proxy for volatility measure
    timeframe: "1h"
    length: 14
  
  # Mean reversion indicator
  - id: "RSI_Mean"
    type: "RSI"
    timeframe: "15m"
    length: 21

logic:
  entry_long:
    # Bear market conditions: Only trade mean reversion setups
    - "ADX_Daily_ADX_value < 25"                # Ranging/weak trend market
    
    # Price at key support levels
    - "close <= VP_Bear_val_price * 1.005"     # Near or below Value Area Low
    - "close > VP_Bear_val_price * 0.995"      # But not too far below
    
    # Mean reversion setup
    - "RSI_Mean < 35"                          # Oversold condition
    - "RSI_Mean > 20"                          # But not extremely oversold
    
    # Volume spike for reversal
    - "volume > VP_Bear_average_volume * 1.3"  # Above average volume
    
    # Trend alignment (cautious in bear markets)
    - "close > EMA_Fast"                       # Above short-term EMA
    
    # Additional safety: not in extreme downtrend
    - "EMA_Fast > EMA_Slow * 0.95"             # EMAs not too diverged
  
  exit_long:
    # Quick exits in bear markets
    - "close > VP_Bear_vah_price"              # Reached Value Area High
    - "RSI_Mean > 65"                          # Overbought
    - "close < VP_Bear_val_price * 0.99"       # Stop loss below VAL
    - "EMA_Fast < EMA_Medium"                  # Trend deterioration
  
  entry_short:
    # Bear market conditions: Trend following in downtrends
    - "ADX_Daily_ADX_value > 20"               # Some trend strength
    - "EMA_Fast < EMA_Medium"                  # Downtrend structure
    - "EMA_Medium < EMA_Slow"                  # Longer-term downtrend
    
    # Price at resistance levels
    - "close >= VP_Bear_vah_price * 0.995"     # Near Value Area High
    - "close < VP_Bear_vah_price * 1.005"      # But not too far above
    
    # Momentum confirmation
    - "RSI_Mean > 65"                          # Overbought for rejection
    - "RSI_Mean < 80"                          # Not extremely overbought
    
    # Volume confirmation
    - "volume > VP_Bear_average_volume * 1.2"  # Volume spike
  
  exit_short:
    # Profit taking and stops
    - "close < VP_Bear_val_price"              # Reached Value Area Low
    - "RSI_Mean < 40"                          # Oversold
    - "close > VP_Bear_vah_price * 1.01"       # Stop loss above VAH
    - "EMA_Fast > EMA_Medium"                  # Trend reversal

# Conservative risk management for bear markets
risk_management:
  enabled: true
  risk_pct: 0.01               # Very conservative 1% per trade
  max_position_pct: 0.15       # Max 15% position size
  use_position_sizing: true
  
  stop_loss:
    base_percent: 0.02         # Tight 2% stop loss
    atr_based: true
    atr_multiplier: 1.5        # Conservative ATR multiplier
  
  take_profit:
    base_percent: 0.03         # Quick 3% profit target
    
    # Multiple profit taking levels
    partial_exits:
      - level: 0.015           # 1.5% target
        percent: 0.5           # Close 50% of position
      - level: 0.025           # 2.5% target  
        percent: 0.3           # Close 30% more

# Bear market specific filters
market_filters:
  # Only trade in lower volatility environments
  max_atr_threshold: 0.08      # Avoid high volatility > 8%
  
  # Volume requirements
  min_volume_multiple: 1.1     # Minimum volume requirement
  
  # Regime filters
  bear_market_mode: true       # Enable bear market specific logic
  max_position_correlation: 0.7 # Reduce correlation exposure

backtest:
  cash: 50000
  commission: 0.0004
  from: "2021-01-01"
  to: "2025-01-01"