# Equity Protection Demo Configuration
# This configuration demonstrates the equity protection system that prevents
# catastrophic drawdowns by implementing first-loss stop functionality.

name: "Equity Protection Demo Strategy"
description: "VP-FVG strategy with comprehensive equity protection against catastrophic drawdowns"

# Data Configuration
symbol: "BTC/USD"
exchange: "binanceus"

# Timeframes
timeframes:
  entry: "1h"
  higher: "4h"

# Indicators Configuration
indicators:
  # Volume Profile for market structure
  - id: "vp"
    type: "VolumeProfile"
    timeframe: "1h"
    period: 24
    value_area_percent: 70
    
  # Fair Value Gap detection
  - id: "fvg"
    type: "FVG"
    timeframe: "1h"
    min_gap_size: 0.001
    max_age: 100
    
  # VP-FVG confluence signal
  - id: "vpfvg"
    type: "VPFVGSignal"
    timeframe: "1h"
    vp_period: 24
    fvg_min_gap: 0.001
    fvg_max_age: 100
    atr_period: 14
    min_volume_threshold: 1000
    
  # ADX for trend strength
  - id: "adx"
    type: "ADX"
    timeframe: "4h"
    period: 14
    threshold: 25

# Equity Protection Configuration
equity_protection:
  enabled: true
  drawdown_threshold: 0.25                    # 25% first-loss stop
  enable_on_bias_flip: true                   # Re-enable trading on bias flip
  smoothing_window: 5                         # 5-period smoothing to avoid noise
  min_equity_history: 10                      # Minimum 10 updates before protection activates
  flatten_positions_on_trigger: true          # Automatically flatten all positions
  disable_new_entries: true                   # Disable new entries when protection active
  recovery_mechanism: "bias_flip"             # Recovery based on bias flip detection
  
  # Bias detection settings
  bias_detection:
    method: "adx_trend"                       # Use ADX for trend/bias detection
    adx_threshold: 25                         # ADX > 25 for strong trend
    price_ma_period: 50                       # 50-period MA for trend direction
    
  # Emergency controls
  emergency_controls:
    force_reset_after_hours: 168              # Force reset after 7 days (168 hours)
    max_consecutive_triggers: 3               # Max 3 consecutive triggers before manual review
    alert_on_trigger: true                    # Alert when protection triggers

# Risk Management Configuration
risk_management:
  # Position sizing with equity protection integration
  risk_pct: 0.015                             # 1.5% risk per trade (slightly higher since we have protection)
  max_position_pct: 0.25                     # Maximum 25% of equity per position
  
  # Stop loss configuration
  atr_stop_multiplier: 2.0                   # 2.0 ATR stop distance
  min_stop_distance_pct: 0.002               # Minimum 0.2% stop distance
  max_stop_distance_pct: 0.08                # Maximum 8% stop distance
  
  # Position limits under protection
  protection_mode:
    max_position_pct: 0.1                    # Reduce max position to 10% when recovering
    risk_pct: 0.005                          # Reduce risk to 0.5% when recovering
    require_stronger_signals: true           # Require stronger confluence when recovering

# Trading Logic with Equity Protection Integration
logic:
  # Long Entry Conditions
  entry_long:
    - "vpfvg_vf_long == True"                # VP-FVG long signal
    - "adx_adx > 25"                         # Strong trend (ADX > 25)
    - "vpfvg_vf_atr > 0"                     # Valid ATR for stop calculation
    - "not equity_protection_active"         # No equity protection active
    - "not trading_disabled"                 # Trading not disabled
    
  # Long Exit Conditions  
  exit_long:
    - "vpfvg_vf_long == False"               # VP-FVG signal reversal
    - "adx_adx < 20"                         # Trend weakening
    - "equity_protection_triggered"          # Equity protection triggered
    - "flatten_all_positions"                # Emergency flatten signal
    
  # Short Entry Conditions
  entry_short:
    - "vpfvg_vf_short == True"               # VP-FVG short signal
    - "adx_adx > 25"                         # Strong trend (ADX > 25)
    - "vpfvg_vf_atr > 0"                     # Valid ATR for stop calculation
    - "not equity_protection_active"         # No equity protection active
    - "not trading_disabled"                 # Trading not disabled
    
  # Short Exit Conditions
  exit_short:
    - "vpfvg_vf_short == False"              # VP-FVG signal reversal
    - "adx_adx < 20"                         # Trend weakening
    - "equity_protection_triggered"          # Equity protection triggered
    - "flatten_all_positions"                # Emergency flatten signal

# Bias Detection Logic for Recovery
bias_detection:
  # Bull bias conditions
  bull_conditions:
    - "adx_adx > 25"                         # Strong trend
    - "close > sma_50"                       # Price above 50-period MA
    - "adx_di_plus > adx_di_minus"           # Positive DI > Negative DI
    
  # Bear bias conditions
  bear_conditions:
    - "adx_adx > 25"                         # Strong trend
    - "close < sma_50"                       # Price below 50-period MA
    - "adx_di_minus > adx_di_plus"           # Negative DI > Positive DI
    
  # Neutral bias (no strong trend)
  neutral_conditions:
    - "adx_adx <= 25"                        # Weak trend

# Backtesting Configuration
backtest:
  from: "2024-01-01"
  to: "2024-12-31"
  initial_cash: 10000
  commission: 0.001
  slippage: 0.0
  
  # Equity protection specific settings
  equity_protection_enabled: true
  track_drawdown_history: true
  generate_protection_report: true
  
  # Enhanced monitoring
  monitor_equity_curve: true
  alert_on_large_drawdowns: true
  save_protection_events: true

# Performance Targets (adjusted for protection)
targets:
  # Risk metrics (more conservative due to protection)
  max_drawdown: 0.25                         # 25% max drawdown (same as protection threshold)
  target_sharpe: 1.2                         # Target Sharpe ratio >= 1.2
  max_protection_triggers: 2                 # Maximum 2 protection triggers per year
  
  # Return metrics
  min_annual_return: 0.15                    # Minimum 15% annual return
  target_win_rate: 0.55                      # Target 55% win rate
  
  # Recovery metrics
  max_recovery_time_days: 30                 # Maximum 30 days to recover from protection
  avg_recovery_time_days: 10                 # Average 10 days recovery time

# Alert Configuration
alerts:
  equity_protection_triggered:
    enabled: true
    message: "EQUITY PROTECTION TRIGGERED - All positions flattened, trading disabled"
    severity: "critical"
    
  drawdown_warning:
    enabled: true
    threshold: 0.15                          # Alert at 15% drawdown
    message: "High drawdown detected - approaching protection threshold"
    severity: "warning"
    
  bias_flip_recovery:
    enabled: true
    message: "Bias flip detected - trading re-enabled after protection"
    severity: "info"
    
  protection_reset:
    enabled: true
    message: "Equity protection reset - normal trading resumed"
    severity: "info"

# Documentation
documentation:
  strategy_overview: |
    Equity Protection Demo Strategy
    
    This strategy demonstrates the comprehensive equity protection system designed
    to prevent catastrophic drawdowns like the 63% loss scenario. The system:
    
    1. **Monitors Equity Curve**: Continuously tracks portfolio equity and calculates
       real-time drawdown from peak equity.
    
    2. **First-Loss Stop**: Triggers protection when drawdown exceeds 25% threshold,
       automatically flattening all positions and disabling new entries.
    
    3. **Bias-Based Recovery**: Re-enables trading only when market bias flips from
       bear to bull (or vice versa), using ADX and directional indicators.
    
    4. **Smart Position Sizing**: Integrates with risk-based position sizing to
       ensure consistent risk exposure across all trades.
    
    5. **Emergency Controls**: Provides manual override and force reset capabilities
       for exceptional market conditions.
  
  protection_logic: |
    Equity Protection Logic Flow:
    
    1. **Normal Trading**: Strategy executes normally with standard entry/exit rules
    
    2. **Drawdown Detection**: System calculates drawdown as (Peak - Current) / Peak
    
    3. **Protection Trigger**: When drawdown >= 25%:
       - Immediately flatten all open positions
       - Disable new long and short entries
       - Set protection_active = True
       - Log trigger event with timestamp and equity level
    
    4. **Recovery Detection**: Monitor for bias flip using ADX indicators:
       - Bull bias: ADX > 25, +DI > -DI, Price > MA(50)
       - Bear bias: ADX > 25, -DI > +DI, Price < MA(50)
       - Neutral: ADX <= 25
    
    5. **Trading Resume**: On bias flip from previous direction:
       - Re-enable new entries (protection_active remains True)
       - trading_disabled = False
       - Resume normal position sizing
    
    6. **Full Reset**: Manual reset or time-based reset clears all protection state
  
  risk_management: |
    Risk Management with Equity Protection:
    
    The equity protection system works in conjunction with position sizing to provide
    multiple layers of risk management:
    
    **Layer 1 - Position Sizing**: Each trade risks 1.5% of equity with ATR-based stops
    **Layer 2 - Stop Losses**: Mechanical stops at 2.0 ATR from entry price
    **Layer 3 - Signal Reversal**: Exit on VP-FVG signal reversal or trend weakening
    **Layer 4 - Equity Protection**: Emergency stop at 25% drawdown from peak
    
    This multi-layered approach ensures that:
    - Individual trades have limited risk exposure
    - Mechanical stops prevent runaway losses
    - Signal-based exits capture trend changes
    - Equity protection prevents catastrophic account loss
    
    The system is designed to survive extreme market conditions while preserving
    capital for recovery during favorable periods.

# Version and Metadata
version: "1.0"
created_date: "2024-01-01"
last_modified: "2024-01-01"
author: "BTC Research Framework"
compatibility:
  min_engine_version: "1.0"
  required_indicators: ["VolumeProfile", "FVG", "VPFVGSignal", "ADX"]
  required_modules: ["equity_protection", "position_sizing", "risk_management"]