# FVG Fair Value Gap Strategy Configuration - Focused Optimization
# This configuration focuses on the 3 most impactful parameters

version: "1.0"
name: "FVG Gap Trading Strategy (Focused)"
symbol: "BTC/USDC"
exchange: "binanceus"

# Named timeframes for this strategy
timeframes:
  structure: "1h"    # Higher timeframe for market structure
  entry: "15m"       # Lower timeframe for precise entries

# Indicators to compute
indicators:
  # EMA for trend bias on higher timeframe
  - id: "EMA_50"
    type: "EMA"
    timeframe: "1h"
    length: 50         # Will be optimized

  # FVG detection on entry timeframe
  - id: "FVG_15m"
    type: "FVG"
    timeframe: "15m"
    min_gap_pips: 10.0     # Will be optimized
    max_lookback: 200      # Fixed value

  # RSI for confluence
  - id: "RSI_14"
    type: "RSI"
    timeframe: "15m"
    length: 14         # Will be optimized

# Trading logic expressions
logic:
  entry_long:
    - "EMA_50_trend == 'bull'"                    # Bullish trend on 1h
    - "FVG_15m_FVG_bullish_signal == True"       # Price at bullish FVG zone
    - "FVG_15m_FVG_active_bullish_gaps > 0"      # Active unfilled bullish gaps
    - "RSI_14 < 50"                              # RSI confirmation (not overbought)
  
  exit_long:
    - "FVG_15m_FVG_gap_filled == True"           # Gap gets filled (take profit)
    - "RSI_14 > 80"                              # Strong overbought condition
  
  entry_short:
    - "EMA_50_trend == 'bear'"                   # Bearish trend on 1h  
    - "FVG_15m_FVG_bearish_signal == True"       # Price at bearish FVG zone
    - "FVG_15m_FVG_active_bearish_gaps > 0"      # Active unfilled bearish gaps
    - "RSI_14 > 50"                              # RSI confirmation (not oversold)
  
  exit_short:
    - "FVG_15m_FVG_gap_filled == True"           # Gap gets filled (take profit)
    - "RSI_14 < 20"                              # Strong oversold condition

# Focused optimization parameters - only the most impactful ones
optimization:
  parameters:
    # EMA trend detection period
    - name: "EMA_50.length"
      type: "integer"
      low: 20
      high: 200
      default: 50
      description: "EMA period for trend detection"
    
    # FVG minimum gap size  
    - name: "FVG_15m.min_gap_pips"
      type: "float"
      low: 5.0
      high: 30.0
      default: 10.0
      description: "Minimum gap size in USD for valid FVG"
    
    # RSI period
    - name: "RSI_14.length"
      type: "integer"
      low: 10
      high: 30
      default: 14
      description: "RSI calculation period"

# Backtesting parameters
backtest:
  cash: 10000          # Starting capital in USD
  commission: 0.0004   # 0.04% commission per trade
  slippage: 0.001      # 0.1% slippage for market orders
  from: "2024-01-01"   # Start date
  to: "2025-01-01"     # End date