# Improved Working Strategy V1
# Based on working FVG+VP pattern with enhanced risk management

version: "2.0"
name: "Improved Working Strategy V1"
symbol: "BTC/USDT"
exchange: "binanceus"

timeframes:
  entry: "15m"
  analysis: "1h"

indicators:
  # Core Volume Profile - same as working version
  - id: "VP_5D"
    type: "VolumeProfile"
    timeframe: "15m"
    lookback: 480         # 5 days
    price_bins: 100
    value_area_pct: 70
    update_frequency: 4
    min_volume_threshold: 0.5
    atr_period: 14
    atr_multiplier: 2.0
  
  # Enhanced FVG - same as working version
  - id: "FVG_Enhanced"
    type: "FVG"
    timeframe: "15m"
    min_gap_pips: 0.001       # Minimum gap size (0.1%)
    min_gap_atr_mult: 0.25    # ATR multiplier for dynamic gap sizing
    max_lookback: 50          # Maximum gaps to track
  
  # Trend filters
  - id: "EMA_20"
    type: "EMA"
    timeframe: "15m"
    length: 20
  
  - id: "EMA_50"
    type: "EMA"
    timeframe: "1h"
    length: 50
  
  # Market regime detection
  - id: "ADX_14"
    type: "ADX"
    timeframe: "1h"
    period: 14
    trend_threshold: 25
    range_threshold: 20
  
  # Momentum filter
  - id: "RSI_14"
    type: "RSI"
    timeframe: "15m"
    length: 14

logic:
  entry_long:
    # Core working signals
    - "FVG_Enhanced_FVG_bullish_signal"
    - "close > EMA_20"
    - "volume > VP_5D_average_volume * 1.1"
    
    # Additional filters for improvement
    - "close > EMA_50"                    # Higher timeframe trend
    - "RSI_14 > 35"                       # Not oversold
    - "RSI_14 < 75"                       # Not overbought
    - "ADX_14_ADX_value > 15"             # Some trend strength
  
  exit_long:
    # Original exits
    - "FVG_Enhanced_FVG_bearish_signal"
    - "close < VP_5D_val_price"
    
    # Additional safety exits
    - "close < EMA_50"                    # Higher TF trend break
    - "RSI_14 > 80"                       # Extreme overbought
  
  entry_short:
    # Core working signals
    - "FVG_Enhanced_FVG_bearish_signal"
    - "close < EMA_20"
    - "volume > VP_5D_average_volume * 1.1"
    
    # Additional filters for improvement
    - "close < EMA_50"                    # Higher timeframe trend
    - "RSI_14 < 65"                       # Not overbought
    - "RSI_14 > 25"                       # Not oversold
    - "ADX_14_ADX_value > 15"             # Some trend strength
  
  exit_short:
    # Original exits
    - "FVG_Enhanced_FVG_bullish_signal"
    - "close > VP_5D_vah_price"
    
    # Additional safety exits
    - "close > EMA_50"                    # Higher TF trend break
    - "RSI_14 < 20"                       # Extreme oversold

# Improved risk management
risk_management:
  enabled: true
  risk_pct: 0.015              # Reduced risk per trade (1.5%)
  max_position_pct: 0.25       # Reduced max position size
  use_position_sizing: true
  
  # Enhanced stops
  stop_loss:
    base_percent: 0.025        # 2.5% base stop
    atr_based: true
    atr_multiplier: 2.0
  
  # Profit taking
  take_profit:
    base_percent: 0.05         # 5% base target
    
    partial_exits:
      - level: 0.025           # 2.5% target
        percent: 0.4           # Close 40% of position
      - level: 0.04            # 4% target
        percent: 0.3           # Close 30% more

backtest:
  cash: 50000
  commission: 0.0004
  from: "2024-06-01"
  to: "2025-01-01"