# Conservative Improved Strategy
# Minimal improvements to the working baseline strategy

version: "2.0"
name: "Conservative Improved Strategy"
symbol: "BTC/USDT"
exchange: "binanceus"

timeframes:
  entry: "15m"
  analysis: "1h"

indicators:
  # Core Volume Profile - exactly same as working version
  - id: "VP_5D"
    type: "VolumeProfile"
    timeframe: "15m"
    lookback: 480         # 5 days
    price_bins: 100
    value_area_pct: 70
    update_frequency: 4
    min_volume_threshold: 0.5
    atr_period: 14
    atr_multiplier: 2.0
  
  # Enhanced FVG - exactly same as working version
  - id: "FVG_Enhanced"
    type: "FVG"
    timeframe: "15m"
    min_gap_pips: 0.001       # Minimum gap size (0.1%)
    min_gap_atr_mult: 0.25    # ATR multiplier for dynamic gap sizing
    max_lookback: 50          # Maximum gaps to track
  
  # EMAs - same as working version
  - id: "EMA_20"
    type: "EMA"
    timeframe: "15m"
    length: 20
  
  # Add only ONE additional filter - simple RSI
  - id: "RSI_14"
    type: "RSI"
    timeframe: "15m"
    length: 14

logic:
  entry_long:
    # Keep ALL original working conditions
    - "FVG_Enhanced_FVG_bullish_signal"
    - "close > EMA_20"
    - "volume > VP_5D_average_volume * 1.1"
    
    # Add only ONE simple additional filter
    - "RSI_14 < 80"                       # Not extremely overbought
  
  exit_long:
    # Keep ALL original working exits
    - "FVG_Enhanced_FVG_bearish_signal"
    - "close < VP_5D_val_price"
    
    # Add ONE additional safety exit
    - "RSI_14 > 85"                       # Extreme overbought
  
  entry_short:
    # Keep ALL original working conditions
    - "FVG_Enhanced_FVG_bearish_signal"
    - "close < EMA_20"
    - "volume > VP_5D_average_volume * 1.1"
    
    # Add only ONE simple additional filter
    - "RSI_14 > 20"                       # Not extremely oversold
  
  exit_short:
    # Keep ALL original working exits
    - "FVG_Enhanced_FVG_bullish_signal"
    - "close > VP_5D_vah_price"
    
    # Add ONE additional safety exit
    - "RSI_14 < 15"                       # Extreme oversold

# Slightly improved risk management (minimal changes)
risk_management:
  enabled: true
  risk_pct: 0.018              # Slightly reduced risk (1.8% vs 2%)
  max_position_pct: 0.3        # Same as original
  use_position_sizing: true
  
  # Add basic profit taking
  take_profit:
    base_percent: 0.06         # 6% take profit
    
    partial_exits:
      - level: 0.03            # 3% target
        percent: 0.5           # Close 50% of position

backtest:
  cash: 50000
  commission: 0.0004
  from: "2024-06-01"
  to: "2025-01-01"