# Simplified VP-FVG Strategy
# Focus: Clean confluence without overcomplications
# Addressing: Overcomplicated confluence strategy issues

version: "2.0"
name: "Simplified VP-FVG Strategy"
symbol: "BTC/USDT"
exchange: "binanceus"

timeframes:
  entry: "15m"
  analysis: "1h"

indicators:
  # Core Volume Profile
  - id: "VP_Core"
    type: "VolumeProfile"
    timeframe: "15m"
    lookback: 480         # 5 days
    price_bins: 60
    value_area_pct: 70
    update_frequency: 4
    min_volume_threshold: 0.5
    atr_period: 14
    atr_multiplier: 2.0
  
  # Simple FVG detection
  - id: "FVG_Simple"
    type: "FVG"
    timeframe: "15m"
    min_gap_pips: 0.002      # 0.2% minimum gap
    min_gap_atr_mult: 0.5    # 0.5x ATR threshold
    max_lookback: 100
  
  # Trend filter
  - id: "EMA_Trend"
    type: "EMA"
    timeframe: "1h"
    length: 50
  
  # Momentum filter
  - id: "RSI_Momentum"
    type: "RSI"
    timeframe: "15m"
    length: 14

logic:
  entry_long:
    # Simple confluence: FVG + VP level + trend
    - "FVG_Simple_FVG_bullish_signal"           # FVG bullish signal
    - "close > VP_Core_poc_price"               # Above POC
    - "close > EMA_Trend"                       # Above trend EMA
    - "RSI_Momentum > 45"                       # Not oversold
    - "RSI_Momentum < 75"                       # Not overbought
    - "volume > VP_Core_average_volume"         # Above average volume
  
  exit_long:
    # Simple exits
    - "close < VP_Core_val_price"               # Below Value Area Low
    - "RSI_Momentum > 85"                       # Extremely overbought
    - "FVG_Simple_FVG_bearish_signal"           # Opposing FVG signal
  
  entry_short:
    # Simple confluence: FVG + VP level + trend
    - "FVG_Simple_FVG_bearish_signal"           # FVG bearish signal
    - "close < VP_Core_poc_price"               # Below POC
    - "close < EMA_Trend"                       # Below trend EMA
    - "RSI_Momentum < 55"                       # Not overbought
    - "RSI_Momentum > 25"                       # Not oversold
    - "volume > VP_Core_average_volume"         # Above average volume
  
  exit_short:
    # Simple exits
    - "close > VP_Core_vah_price"               # Above Value Area High
    - "RSI_Momentum < 15"                       # Extremely oversold
    - "FVG_Simple_FVG_bullish_signal"           # Opposing FVG signal

# Simplified risk management
risk_management:
  enabled: true
  risk_pct: 0.02               # 2% per trade
  max_position_pct: 0.3        # Max 30% position
  use_position_sizing: true
  
  stop_loss:
    base_percent: 0.03         # 3% stop loss
    atr_based: true
    atr_multiplier: 2.5
  
  take_profit:
    base_percent: 0.06         # 6% take profit (2:1 R:R)

backtest:
  cash: 50000
  commission: 0.0004
  from: "2021-01-01"
  to: "2025-01-01"