# Improved Working Strategy V2
# Focus on higher win rate through more selective entries

version: "2.0"
name: "Improved Working Strategy V2 - High Win Rate"
symbol: "BTC/USDT"
exchange: "binanceus"

timeframes:
  entry: "15m"
  analysis: "1h"

indicators:
  # Core Volume Profile - same as working version
  - id: "VP_5D"
    type: "VolumeProfile"
    timeframe: "15m"
    lookback: 480         # 5 days
    price_bins: 100
    value_area_pct: 70
    update_frequency: 4
    min_volume_threshold: 0.5
    atr_period: 14
    atr_multiplier: 2.0
  
  # Enhanced FVG - same as working version
  - id: "FVG_Enhanced"
    type: "FVG"
    timeframe: "15m"
    min_gap_pips: 0.001       # Minimum gap size (0.1%)
    min_gap_atr_mult: 0.25    # ATR multiplier for dynamic gap sizing
    max_lookback: 50          # Maximum gaps to track
  
  # Multiple EMAs for better trend confirmation
  - id: "EMA_20"
    type: "EMA"
    timeframe: "15m"
    length: 20
  
  - id: "EMA_50"
    type: "EMA"
    timeframe: "15m"
    length: 50
  
  - id: "EMA_100"
    type: "EMA"
    timeframe: "1h"
    length: 100
  
  # Momentum filters
  - id: "RSI_14"
    type: "RSI"
    timeframe: "15m"
    length: 14

logic:
  entry_long:
    # Core working signals (required)
    - "FVG_Enhanced_FVG_bullish_signal"
    - "close > EMA_20"
    - "volume > VP_5D_average_volume * 1.2"    # Higher volume requirement
    
    # Strong trend alignment for higher win rate
    - "EMA_20 > EMA_50"                        # Short > medium EMA
    - "EMA_50 > EMA_100"                       # Medium > long EMA
    - "close > EMA_100"                        # Price above all EMAs
    
    # Quality filters
    - "close > VP_5D_poc_price"                # Above POC for strength
    - "RSI_14 > 40"                            # Not oversold
    - "RSI_14 < 70"                            # Not overbought
    
    # Volume Profile confluence
    - "close < VP_5D_vah_price * 1.02"         # Not too extended above VAH
  
  exit_long:
    # Quick profit taking for higher win rate
    - "FVG_Enhanced_FVG_bearish_signal"        # Opposing signal
    - "close < VP_5D_val_price"                # Below VAL
    - "EMA_20 < EMA_50"                        # Trend deterioration
    - "RSI_14 > 75"                            # Overbought
  
  entry_short:
    # Core working signals (required)
    - "FVG_Enhanced_FVG_bearish_signal"
    - "close < EMA_20"
    - "volume > VP_5D_average_volume * 1.2"    # Higher volume requirement
    
    # Strong downtrend alignment for higher win rate
    - "EMA_20 < EMA_50"                        # Short < medium EMA
    - "EMA_50 < EMA_100"                       # Medium < long EMA
    - "close < EMA_100"                        # Price below all EMAs
    
    # Quality filters
    - "close < VP_5D_poc_price"                # Below POC for strength
    - "RSI_14 < 60"                            # Not overbought
    - "RSI_14 > 30"                            # Not oversold
    
    # Volume Profile confluence
    - "close > VP_5D_val_price * 0.98"         # Not too extended below VAL
  
  exit_short:
    # Quick profit taking for higher win rate
    - "FVG_Enhanced_FVG_bullish_signal"        # Opposing signal
    - "close > VP_5D_vah_price"                # Above VAH
    - "EMA_20 > EMA_50"                        # Trend deterioration
    - "RSI_14 < 25"                            # Oversold

# Aggressive profit taking for higher win rate
risk_management:
  enabled: true
  risk_pct: 0.02               # 2% per trade
  max_position_pct: 0.3        # 30% max position
  use_position_sizing: true
  
  # Quick profit taking
  take_profit:
    base_percent: 0.04         # 4% base target (2:1 R:R)
    
    # Staged exits for higher win rate
    partial_exits:
      - level: 0.015           # 1.5% target
        percent: 0.5           # Close 50% of position
      - level: 0.03            # 3% target
        percent: 0.3           # Close 30% more
      - level: 0.045           # 4.5% target
        percent: 0.2           # Close remaining 20%
  
  # Tight stops
  stop_loss:
    base_percent: 0.02         # 2% stop loss

backtest:
  cash: 50000
  commission: 0.0004
  from: "2024-06-01"
  to: "2025-01-01"