# Improved Volume Profile Breakout Strategy V1
# Focus: Enhanced Risk Management & Market Regime Filtering
# Addressing: Poor bear market performance, high drawdowns

version: "2.0"
name: "Improved Volume Profile Breakout V1"
symbol: "BTC/USDT"
exchange: "binanceus"

timeframes:
  entry: "15m"
  analysis: "1h"
  regime: "4h"  # Higher timeframe for better regime detection

indicators:
  # Enhanced Volume Profile with better parameters
  - id: "VP_Main"
    type: "VolumeProfile"
    timeframe: "15m"
    lookback: 672         # 7 days (extended for better levels)
    price_bins: 80        # More granular bins
    value_area_pct: 70
    update_frequency: 4
    min_volume_threshold: 0.3
    atr_period: 14
    atr_multiplier: 1.5   # More conservative breakout threshold
  
  # Market Structure EMAs for trend filtering
  - id: "EMA_Fast"
    type: "EMA"
    timeframe: "1h"
    length: 21
  
  - id: "EMA_Slow"
    type: "EMA"
    timeframe: "1h"
    length: 55
  
  # Market regime detection with ADX
  - id: "ADX_Regime"
    type: "ADX"
    timeframe: "4h"
    period: 14
    trend_threshold: 25
    range_threshold: 18
  
  # RSI for momentum confirmation
  - id: "RSI_Main"
    type: "RSI"
    timeframe: "15m"
    length: 14
  
  # Volume confirmation
  - id: "Volume_SMA"
    type: "EMA"
    timeframe: "15m"
    length: 20

logic:
  entry_long:
    # Strong trend requirement
    - "EMA_Fast > EMA_Slow"
    
    # Volume Profile breakout
    - "close > VP_Main_poc_price"
    - "close > VP_Main_vah_price"
    
    # Volume confirmation (stronger requirement)
    - "volume > Volume_SMA * 1.5"
    
    # Market regime filter (only trade in trending markets)
    - "ADX_Regime_ADX_value > 25"
    - "ADX_Regime_DI_plus > ADX_Regime_DI_minus"
    
    # Momentum confirmation
    - "RSI_Main > 55"
    - "RSI_Main < 80"
  
  exit_long:
    # Trend deterioration
    - "EMA_Fast < EMA_Slow"
    
    # Volume Profile level break
    - "close < VP_Main_val_price"
    
    # Momentum loss
    - "RSI_Main < 45"
  
  entry_short:
    # Strong downtrend requirement
    - "EMA_Fast < EMA_Slow"
    
    # Volume Profile breakdown
    - "close < VP_Main_poc_price"
    - "close < VP_Main_val_price"
    
    # Volume confirmation
    - "volume > Volume_SMA * 1.5"
    
    # Market regime filter
    - "ADX_Regime_ADX_value > 25"
    - "ADX_Regime_DI_minus > ADX_Regime_DI_plus"
    
    # Momentum confirmation
    - "RSI_Main < 45"
    - "RSI_Main > 20"
  
  exit_short:
    # Trend reversal
    - "EMA_Fast > EMA_Slow"
    
    # Volume Profile level reclaim
    - "close > VP_Main_vah_price"
    
    # Momentum reversal
    - "RSI_Main > 55"

# Enhanced Risk Management
risk_management:
  enabled: true
  risk_pct: 0.015              # Reduced to 1.5% per trade
  max_position_pct: 0.25       # Max 25% of portfolio
  use_position_sizing: true
  
  # Dynamic stops based on market regime
  stop_loss:
    base_percent: 0.025        # 2.5% base stop
    atr_based: true
    atr_multiplier: 2.0
    
    # Regime-based adjustments
    trending_multiplier: 1.3   # Wider stops in trending markets
    ranging_multiplier: 0.8    # Tighter stops in ranging markets
  
  take_profit:
    base_percent: 0.05         # 5% base target (2:1 R:R)
    use_vp_targets: true
    
    # Partial profit taking
    partial_exits:
      - level: 0.025           # 2.5% target
        percent: 0.4           # Close 40% of position
      - level: 0.04            # 4% target
        percent: 0.3           # Close 30% more

# Market Condition Filters
market_filters:
  # Volatility filter
  min_atr_threshold: 0.02      # Only trade when ATR > 2%
  max_atr_threshold: 0.15      # Avoid extreme volatility > 15%
  
  # Trend strength requirement
  min_adx_for_entry: 25        # Minimum ADX for entries
  
  # Volume requirement
  min_volume_multiple: 1.2     # Minimum 1.2x average volume

backtest:
  cash: 50000
  commission: 0.0004
  from: "2021-01-01"
  to: "2025-01-01"