# Multi-Timeframe Volume Profile Enhanced Strategy
# Focus: Improved win rate through better confluence
# Addressing: Low ~30% win rate across all periods

version: "2.0"
name: "Multi-Timeframe VP Enhanced"
symbol: "BTC/USDT"
exchange: "binanceus"

timeframes:
  entry: "15m"
  structure: "1h"
  bias: "4h"

indicators:
  # Short-term Volume Profile for entries
  - id: "VP_Entry"
    type: "VolumeProfile"
    timeframe: "15m"
    lookback: 288         # 3 days
    price_bins: 80
    value_area_pct: 70
    update_frequency: 2
    min_volume_threshold: 0.3
    atr_period: 14
    atr_multiplier: 1.8
  
  # Medium-term Volume Profile for structure
  - id: "VP_Structure"
    type: "VolumeProfile"
    timeframe: "1h"
    lookback: 168         # 7 days on 1h
    price_bins: 60
    value_area_pct: 70
    update_frequency: 4
    min_volume_threshold: 0.5
    atr_period: 14
    atr_multiplier: 2.0
  
  # Long-term Volume Profile for bias
  - id: "VP_Bias"
    type: "VolumeProfile"
    timeframe: "4h"
    lookback: 84          # 2 weeks on 4h
    price_bins: 40
    value_area_pct: 68
    update_frequency: 6
    min_volume_threshold: 0.8
    atr_period: 14
    atr_multiplier: 2.5
  
  # Trend structure indicators
  - id: "EMA_Short"
    type: "EMA"
    timeframe: "15m"
    length: 21
  
  - id: "EMA_Medium"
    type: "EMA"
    timeframe: "1h"
    length: 34
  
  - id: "EMA_Long"
    type: "EMA"
    timeframe: "4h"
    length: 55
  
  # Quality filters
  - id: "RSI_Quality"
    type: "RSI"
    timeframe: "15m"
    length: 14
  
  - id: "ADX_Strength"
    type: "ADX"
    timeframe: "1h"
    period: 14
    trend_threshold: 25
    range_threshold: 20

logic:
  entry_long:
    # Multi-timeframe trend alignment (improves win rate)
    - "close > EMA_Short"                       # 15m trend up
    - "close > EMA_Medium"                      # 1h trend up  
    - "close > EMA_Long"                        # 4h trend up
    
    # Multi-timeframe VP confluence
    - "close > VP_Entry_poc_price"              # Above entry POC
    - "close > VP_Structure_val_price"          # Above structure VAL
    - "VP_Bias_poc_price < VP_Structure_poc_price"  # Bias POC below structure (uptrend)
    
    # Quality filters (improve win rate)
    - "RSI_Quality > 45"                        # Not oversold
    - "RSI_Quality < 70"                        # Not overbought
    - "ADX_Strength_ADX_value > 20"             # Minimum trend strength
    - "ADX_Strength_DI_plus > ADX_Strength_DI_minus"  # Uptrend confirmed
    
    # Volume confirmation across timeframes
    - "volume > VP_Entry_average_volume * 1.2"  # Entry timeframe volume
    
    # Additional confluence: Price between key levels
    - "close < VP_Structure_vah_price * 1.02"   # Not too extended above VAH
    
    # Market structure: Higher lows pattern
    - "VP_Entry_val_price > VP_Entry_val_price[24]"  # VAL rising (24 periods = 6h ago)
  
  exit_long:
    # Multi-timeframe exit signals
    - "close < VP_Entry_val_price"              # Below entry VAL
    - "close < EMA_Short"                       # Below short-term trend
    - "RSI_Quality > 80"                        # Extremely overbought
    - "ADX_Strength_DI_minus > ADX_Strength_DI_plus"  # Trend reversal
    
    # Structure break
    - "close < VP_Structure_poc_price * 0.995"  # Break of structure POC
  
  entry_short:
    # Multi-timeframe trend alignment
    - "close < EMA_Short"                       # 15m trend down
    - "close < EMA_Medium"                      # 1h trend down
    - "close < EMA_Long"                        # 4h trend down
    
    # Multi-timeframe VP confluence
    - "close < VP_Entry_poc_price"              # Below entry POC
    - "close < VP_Structure_vah_price"          # Below structure VAH
    - "VP_Bias_poc_price > VP_Structure_poc_price"  # Bias POC above structure (downtrend)
    
    # Quality filters
    - "RSI_Quality < 55"                        # Not overbought
    - "RSI_Quality > 30"                        # Not oversold
    - "ADX_Strength_ADX_value > 20"             # Minimum trend strength
    - "ADX_Strength_DI_minus > ADX_Strength_DI_plus"  # Downtrend confirmed
    
    # Volume confirmation
    - "volume > VP_Entry_average_volume * 1.2"
    
    # Additional confluence
    - "close > VP_Structure_val_price * 0.98"   # Not too extended below VAL
    
    # Market structure: Lower highs pattern
    - "VP_Entry_vah_price < VP_Entry_vah_price[24]"  # VAH falling
  
  exit_short:
    # Multi-timeframe exit signals
    - "close > VP_Entry_vah_price"              # Above entry VAH
    - "close > EMA_Short"                       # Above short-term trend
    - "RSI_Quality < 20"                        # Extremely oversold
    - "ADX_Strength_DI_plus > ADX_Strength_DI_minus"  # Trend reversal
    
    # Structure break
    - "close > VP_Structure_poc_price * 1.005"  # Break of structure POC

# Balanced risk management for higher win rate
risk_management:
  enabled: true
  risk_pct: 0.018              # 1.8% per trade
  max_position_pct: 0.25       # Max 25% position
  use_position_sizing: true
  
  stop_loss:
    base_percent: 0.025        # 2.5% stop loss
    atr_based: true
    atr_multiplier: 2.0
    
    # Use VP levels for dynamic stops
    use_vp_levels: true
    vp_buffer: 0.002           # 0.2% buffer beyond VP levels
  
  take_profit:
    base_percent: 0.045        # 4.5% take profit (1.8:1 R:R)
    use_vp_targets: true       # Use opposite VP levels as targets
    
    # Staged profit taking for higher win rate
    partial_exits:
      - level: 0.02            # 2% target
        percent: 0.3           # Close 30% of position
      - level: 0.035           # 3.5% target
        percent: 0.4           # Close 40% more
      - level: 0.05            # 5% target
        percent: 0.3           # Close remaining 30%

# Enhanced filters for quality trades
market_filters:
  # Volatility requirements
  min_atr_threshold: 0.015     # Minimum 1.5% ATR
  max_atr_threshold: 0.12      # Maximum 12% ATR
  
  # Volume requirements
  min_volume_multiple: 1.15    # Minimum volume requirement
  
  # Trend quality
  min_adx_for_entry: 20        # Minimum ADX for entries
  
  # Multi-timeframe alignment score
  min_alignment_score: 0.7     # Require 70% timeframe alignment

# Trade timing optimization
timing_filters:
  # Avoid trading during low liquidity hours
  avoid_asian_session: true
  
  # Prefer trading during high activity periods
  prefer_overlap_sessions: true
  
  # News avoidance (if news data available)
  avoid_major_news: true

backtest:
  cash: 50000
  commission: 0.0004
  from: "2021-01-01"
  to: "2025-01-01"