# Simple RSI strategy for testing
# This is a minimal configuration using only RSI indicator
# Useful for testing the configuration system

version: "1.0"
name: "Simple RSI Strategy"
symbol: "BTC/USDC"
exchange: "binanceus"

# Single timeframe strategy
timeframes:
  entry: "15m"

# Single RSI indicator
indicators:
  - id: "RSI_14"
    type: "RSI"
    timeframe: "15m"
    length: 14

# Simple RSI mean reversion logic
logic:
  entry_long:
    - "RSI_14 < 30"    # Buy when oversold
  
  exit_long:
    - "RSI_14 > 70"    # Sell when overbought
  
  entry_short:
    - "RSI_14 > 70"    # Short when overbought
  
  exit_short:
    - "RSI_14 < 30"    # Cover when oversold

# Conservative backtesting parameters
backtest:
  cash: 5000
  commission: 0.001    # 0.1% commission
  slippage: 0.0005     # 0.05% slippage
  from: "2024-03-01"
  to: "2024-05-31"