# Simple FVG Indicator Configuration
# Basic Fair Value Gap detection for testing and analysis

version: "1.0"
name: "Simple FVG Detection"
symbol: "BTC/USDC"
exchange: "binanceus"

# Single timeframe strategy
timeframes:
  entry: "5m"    # 5-minute timeframe for gap detection

# Indicators to compute
indicators:
  # FVG detection only
  - id: "FVG_5m"
    type: "FVG"
    timeframe: "5m"
    min_gap_pips: 5.0      # Minimum 5 pips
    max_lookback: 500      # Track last 500 candles

# Simple trading logic - enter on any FVG signal
logic:
  entry_long:
    - "FVG_5m_FVG_bullish_signal == True"   # Price touches bullish FVG
  
  exit_long:
    - "FVG_5m_FVG_gap_filled == True"       # Exit when gap fills
  
  entry_short:
    - "FVG_5m_FVG_bearish_signal == True"   # Price touches bearish FVG
  
  exit_short:
    - "FVG_5m_FVG_gap_filled == True"       # Exit when gap fills

# Backtesting parameters
backtest:
  cash: 10000          # Starting capital
  commission: 0.0004   # 0.04% commission
  slippage: 0.001      # 0.1% slippage
  from: "2024-01-01"   # Shorter test period
  to: "2024-06-01"     # One month test