# VP-FVG Confluence Strategy - Production Ready
# Advanced confluence system combining Volume Profile, Fair Value Gaps, and ADX
# Regime-aware filtering with multiple strategy variants

version: "2.0"
name: "VP-FVG Confluence Strategy"
symbol: "BTC/USDT"
exchange: "binanceus"

# Multi-timeframe approach for comprehensive analysis
timeframes:
  entry: "15m"
  analysis: "1h"      # Higher timeframe for trend context
  regime: "1h"        # Regime detection timeframe

# VP-FVG Confluence Indicator Chain
indicators:
  # Core Volume Profile - Foundation of the strategy
  - id: "VP_5D"
    type: "VolumeProfile"
    timeframe: "15m"
    lookback: 480         # 5 days (480 * 15m = 5 days)
    price_bins: 100       # Higher resolution for precise levels
    value_area_pct: 70    # Standard 70% Value Area
    update_frequency: 4   # Update every hour for performance
    min_volume_threshold: 0.5    # Filter noise with minimum volume threshold (0.5%)
    atr_period: 14              # ATR period for POC breakout detection
    atr_multiplier: 2.0         # ATR multiplier for breakout threshold
  
  # Enhanced FVG with VP bin-index tagging
  - id: "FVG_Enhanced"
    type: "FVG"
    timeframe: "15m"
    min_gap_pips: 0.001       # Minimum gap size (0.1%)
    min_gap_atr_mult: 0.25    # ATR multiplier for dynamic gap sizing
    max_lookback: 50          # Maximum gaps to track
  
  # VP-FVG Confluence Signal Generator
  - id: "VPFVGSignal"
    type: "VPFVGSignal"
    timeframe: "15m"
    atr_period: 14               # ATR period for distance calculations
    lvn_dist_multiplier: 0.25    # ATR multiplier for LVN proximity
    poc_shift_multiplier: 0.5    # ATR multiplier for POC shift threshold
    hvn_overlap_pct: 0.3         # Minimum overlap for HVN confluence
    min_fvg_size: 1.0            # Minimum FVG size to consider valid
    lookback_validation: 5       # Bars to look back for validation
  
  # ADX for regime detection and trend filtering
  - id: "ADX_14"
    type: "ADX"
    timeframe: "1h"              # Higher timeframe for regime detection
    period: 14                   # Standard ADX period
    trend_threshold: 25          # Above this = trending market
    range_threshold: 20          # Below this = ranging market
  
  # Supporting indicators for confluence
  - id: "EMA_20"
    type: "EMA"
    timeframe: "15m"
    length: 20
  
  - id: "RSI_14"
    type: "RSI"
    timeframe: "15m"
    length: 14

# VP-FVG Confluence Trading Logic with Regime-Aware Filtering
logic:
  # LONG ENTRY CONDITIONS - Simplified for testing
  entry_long:
    # PRIMARY SIGNAL: Use FVG directly since VPFVGSignal has few long signals
    - "FVG_Enhanced_FVG_bullish_signal"
    
    # TREND ALIGNMENT: Price above EMA for trend confirmation
    - "close > EMA_20"
    
    # VOLUME CONFIRMATION: Above average volume
    - "volume > VP_5D_average_volume * 1.1"

  # LONG EXIT CONDITIONS - Simplified
  exit_long:
    # PROFIT TAKING: Opposite FVG signal
    - "FVG_Enhanced_FVG_bearish_signal"
    
    # STOP LOSS: Price breaks key VP level
    - "close < VP_5D_val_price"

  # SHORT ENTRY CONDITIONS - Simplified for testing
  entry_short:
    # PRIMARY SIGNAL: Use FVG directly
    - "FVG_Enhanced_FVG_bearish_signal"
    
    # TREND ALIGNMENT: Price below EMA for trend confirmation
    - "close < EMA_20"
    
    # VOLUME CONFIRMATION: Above average volume
    - "volume > VP_5D_average_volume * 1.1"

  # SHORT EXIT CONDITIONS - Simplified
  exit_short:
    # PROFIT TAKING: Opposite FVG signal
    - "FVG_Enhanced_FVG_bullish_signal"
    
    # STOP LOSS: Price breaks key VP level
    - "close > VP_5D_vah_price"

# Strategy Variants for Different Market Conditions
variants:
  # Reversal-focused variant for ranging markets
  reversal_only:
    entry_long:
      - "VPFVGSignal_vf_long"
      - "VPFVGSignal_signal_type == 'reversal'"
      - "ADX_14_ADX_value < 25"  # Ranging market condition
      - "close > EMA_20"
      - "RSI_14 < 75"
      - "volume > VP_5D_average_volume * 1.1"
    
    entry_short:
      - "VPFVGSignal_vf_short"
      - "VPFVGSignal_signal_type == 'reversal'"
      - "ADX_14_ADX_value < 25"  # Ranging market condition
      - "close < EMA_20"
      - "RSI_14 > 25"
      - "volume > VP_5D_average_volume * 1.1"
  
  # Continuation-focused variant for trending markets
  continuation_only:
    entry_long:
      - "VPFVGSignal_vf_long"
      - "VPFVGSignal_signal_type == 'continuation'"
      - "ADX_14_ADX_value > 25"  # Trending market condition
      - "ADX_14_DI_plus > ADX_14_DI_minus"  # Uptrend confirmation
      - "close > EMA_20"
      - "RSI_14 > 50"  # Momentum confirmation
      - "volume > VP_5D_average_volume * 1.2"
    
    entry_short:
      - "VPFVGSignal_vf_short"
      - "VPFVGSignal_signal_type == 'continuation'"
      - "ADX_14_ADX_value > 25"  # Trending market condition
      - "ADX_14_DI_minus > ADX_14_DI_plus"  # Downtrend confirmation
      - "close < EMA_20"
      - "RSI_14 < 50"  # Momentum confirmation
      - "volume > VP_5D_average_volume * 1.2"

# Risk Management with Regime-Aware Adjustments
risk_management:
  # Position sizing based on market regime
  position_size:
    base_size: 0.1  # Base position size (10% of capital)
    
    # Adjust position size based on ADX regime
    regime_adjustments:
      trending: 1.2   # 20% larger positions in trending markets
      ranging: 0.8    # 20% smaller positions in ranging markets
      uncertain: 0.5  # 50% smaller positions when regime unclear
    
    # Signal strength adjustments
    signal_strength_multiplier: true  # Scale by VPFVGSignal_signal_strength
  
  # Stop loss with VP-aware levels
  stop_loss:
    base_percent: 0.02  # Base 2% stop loss
    
    # Use VP levels for dynamic stops
    use_vp_levels: true
    vp_buffer: 0.001   # 0.1% buffer beyond VP levels
    
    # ADX-based stop adjustments
    adx_adjustments:
      trending: 1.5    # Wider stops in trending markets
      ranging: 0.8     # Tighter stops in ranging markets
  
  # Take profit with confluence-based targets
  take_profit:
    base_percent: 0.04  # Base 4% take profit
    
    # Use opposite VP levels for targets
    use_vp_targets: true
    
    # Partial profit taking
    partial_exits:
      - level: 0.02   # 2% target
        percent: 0.3  # Close 30% of position
      - level: 0.03   # 3% target
        percent: 0.5  # Close 50% of remaining position

# Extended backtesting for comprehensive market condition testing
backtest:
  cash: 50000           # Increased capital for realistic position sizing
  commission: 0.0004    # 0.04% commission per trade (realistic for spot)
  from: "2023-01-01"    # Extended 15-month test period
  to: "2024-01-01"      # Captures multiple market phases