# Simple Volume Profile + Order Block Strategy
# Focus: Clean, simple confluence without overcomplications
# Alternative to complex FVG strategies

version: "2.0"
name: "VP-OrderBlock Simple Strategy"
symbol: "BTC/USDT"
exchange: "binanceus"

timeframes:
  entry: "15m"
  structure: "1h"

indicators:
  # Core Volume Profile
  - id: "VP_Main"
    type: "VolumeProfile"
    timeframe: "15m"
    lookback: 480         # 5 days
    price_bins: 60
    value_area_pct: 70
    update_frequency: 4
    min_volume_threshold: 0.5
    atr_period: 14
    atr_multiplier: 2.0
  
  # Simple trend filter
  - id: "EMA_Trend"
    type: "EMA"
    timeframe: "1h"
    length: 50
  
  # Momentum filter
  - id: "RSI_Momentum"
    type: "RSI"
    timeframe: "15m"
    length: 14
  
  # Volume moving average
  - id: "Volume_MA"
    type: "EMA"
    timeframe: "15m"
    length: 20

logic:
  entry_long:
    # Trend alignment
    - "close > EMA_Trend"
    
    # Volume Profile setup - Price reacting from key support
    - "low <= VP_Main_val_price * 1.003"      # Touched or came close to VAL
    - "close > VP_Main_val_price"             # But closed above VAL (rejection)
    
    # Order block concept - Previous red candle's body becomes support
    - "close[1] < open[1]"                    # Previous candle was bearish (order block)
    - "close > high[1]"                       # Current close above prev high (break)
    
    # Volume confirmation
    - "volume > Volume_MA * 1.2"              # Above average volume
    
    # Momentum filter
    - "RSI_Momentum > 40"                     # Not oversold
    - "RSI_Momentum < 75"                     # Not overbought
    
    # Additional confluence - not too extended
    - "close < VP_Main_vah_price * 1.02"      # Not too far above VAH
  
  exit_long:
    # Simple exits
    - "close < VP_Main_val_price * 0.995"     # Break below VAL with buffer
    - "RSI_Momentum > 80"                     # Extremely overbought
    - "close < EMA_Trend"                     # Trend break
  
  entry_short:
    # Trend alignment
    - "close < EMA_Trend"
    
    # Volume Profile setup - Price reacting from key resistance
    - "high >= VP_Main_vah_price * 0.997"     # Touched or came close to VAH
    - "close < VP_Main_vah_price"             # But closed below VAH (rejection)
    
    # Order block concept - Previous green candle's body becomes resistance
    - "close[1] > open[1]"                    # Previous candle was bullish (order block)
    - "close < low[1]"                        # Current close below prev low (break)
    
    # Volume confirmation
    - "volume > Volume_MA * 1.2"              # Above average volume
    
    # Momentum filter
    - "RSI_Momentum < 60"                     # Not overbought
    - "RSI_Momentum > 25"                     # Not oversold
    
    # Additional confluence - not too extended
    - "close > VP_Main_val_price * 0.98"      # Not too far below VAL
  
  exit_short:
    # Simple exits
    - "close > VP_Main_vah_price * 1.005"     # Break above VAH with buffer
    - "RSI_Momentum < 20"                     # Extremely oversold
    - "close > EMA_Trend"                     # Trend break

# Conservative risk management
risk_management:
  enabled: true
  risk_pct: 0.02               # 2% per trade
  max_position_pct: 0.3        # Max 30% position
  use_position_sizing: true
  
  stop_loss:
    base_percent: 0.03         # 3% stop loss
    atr_based: true
    atr_multiplier: 2.0
  
  take_profit:
    base_percent: 0.06         # 6% take profit (2:1 R:R)
    
    # Simple partial exits
    partial_exits:
      - level: 0.03            # 3% target
        percent: 0.5           # Close 50% of position
      - level: 0.05            # 5% target
        percent: 0.3           # Close 30% more

# Market filters
market_filters:
  min_volume_multiple: 1.1     # Minimum volume requirement
  min_atr_threshold: 0.015     # Minimum volatility
  max_atr_threshold: 0.12      # Maximum volatility

backtest:
  cash: 50000
  commission: 0.0004
  from: "2021-01-01"
  to: "2025-01-01"