name: "FVG‑Trend‑Baseline"
symbol: "BTC/USDT"
timeframes:
  entry: 15m
  bias:  1h

indicators:
  - id: FVG
    type: FVG
    timeframe: 15m
    min_gap_pips: 0.05
    min_gap_atr_mult: 0.05

  - id: EMA_1h_100
    type: EMA
    timeframe: 1h
    length: 100

  - id: Risk
    type: RiskManagement
    timeframe: 15m         # unchanged
    atr_period: 14
    initial_stop_atr_mult: 1.0   # ← wider because we have no other filter
    trailing_stop_atr_mult: 0    # OFF
    target_atr_mult: 2.0
    breakeven_r_mult: 999        # effectively OFF
    enable_trailing: false

logic:
  entry_long:
    - FVG_bullish_signal
    - close > EMA_1h_100_EMA_100        # simple bias

  entry_short:
    - FVG_bearish_signal
    - close < EMA_1h_100_EMA_100

  exit_long:
    - Risk_exit_long_risk               # fixed stop/target

  exit_short:
    - Risk_exit_short_risk

backtest:
  cash: 100000
  commission: 0.0004
  from: "2021-11-01"
  to:   "2022-11-01"

risk_management:
  risk_pct: 0.01           # 1 % per trade
  max_position_pct: 0.25
