name: "VP-FVG Confluence Strategy"
description: "A confluence strategy combining Volume Profile and Fair Value Gap indicators to identify high-probability reversal and continuation setups."
symbol: "BTC/USDT"
exchange: "binanceus"

# Multi-timeframe approach for comprehensive analysis
timeframes:
  entry: "15m"
  analysis: "1h"

indicators:
  # Volume Profile - RELAXED PARAMETERS for more frequent signals
  - id: "VolumeProfile"
    type: "VolumeProfile"
    timeframe: "15m"
    lookback: 288                # 3 days = 288 * 15m (reduced from 5 days)
    lookback_hours: 72           # 3 days = 72 hours (reduced from 5 days)
    price_bins: 40               # Reduced from 50 for broader bins
    value_area_pct: 70
    update_frequency: 1
    min_volume_threshold: 0.01
    hvn_threshold: 1.2           # High Volume Node threshold (reduced from 1.5)
    lvn_threshold: 0.6           # Low Volume Node threshold (increased from 0.5)
    atr_period: 14
    atr_multiplier: 2.0
    enable_vectorization: true

  # Fair Value Gap - RELAXED PARAMETERS for more frequent signals
  - id: "FVG"
    type: "FVG"
    timeframe: "15m"
    min_gap_pips: 0.05           # Allow very small absolute gaps
    min_gap_atr_mult: 0.05       # Dynamic threshold at 0.05 × ATR (much looser)
    max_lookback: 500

  # VP-FVG Confluence Signal - Core trading logic (RELAXED PARAMETERS)
  - id: "VPFVGSignal"
    type: "VPFVGSignal"
    timeframe: "15m"
    atr_period: 14
    lvn_dist_multiplier: 0.55    # 0.55 × ATR for LVN proximity (increased from 0.45)
    poc_shift_multiplier: 0.3    # 0.3 × ATR for POC shift threshold (loosened)
    hvn_overlap_pct: 0.03        # 3% overlap for HVN confluence (reduced from 5%)
    min_fvg_size: 0.15           # Minimum FVG size (reduced from 0.25)
    lookback_validation: 20       # Bars to look back for validation
  
  # Risk Management - ATR-based position management with R-multiple system
  - id: "RiskManagement"
    type: "RiskManagement"
    timeframe: "15m"
    atr_period: 14
    initial_stop_atr_mult: 1.0       # Increase from 0.5 to 1.0 ATR for wider stops
    trailing_stop_atr_mult: 1.0      # Keep at 1.0 ATR for trailing
    target_atr_mult: 2.0             # Increase from 1.0 to 2.0 ATR for more realistic targets
    breakeven_r_mult: 0.75           # Move to breakeven at R=0.75 (was 0.5)
    enable_trailing: true            # Enable trailing stop functionality
  
  # ADX Regime Filter - Multi-timeframe bias for reversal vs continuation
  - id: "ADX_15m"
    type: "ADX"
    timeframe: "15m"
    period: 14
    trend_threshold: 25.0        # ADX > 25 indicates trending market
    range_threshold: 20.0        # ADX < 20 indicates ranging market
    smoothing_method: "wilder"   # Wilder's smoothing method
  
  # ADX on higher timeframe for regime filtering
  - id: "ADX_1h"
    type: "ADX"
    timeframe: "1h"
    period: 14
    trend_threshold: 25.0        # ADX > 25 indicates trending market
    range_threshold: 20.0        # ADX < 20 indicates ranging market
    smoothing_method: "wilder"   # Wilder's smoothing method
  
  # EMA 100 on 1h timeframe for shorter-term market bias filtering
  - id: "EMA_1h_100"
    type: "EMA"
    timeframe: "1h"
    length: 100                  # 100-period EMA for shorter-term bias

# VP-FVG Confluence Trading Logic - SIMPLIFIED FOR MORE TRADES
logic:
  # LONG ENTRY CONDITIONS - Simplified and more permissive
  entry_long:
    - "VPFVGSignal_vf_long"                    # Primary confluence signal
    - "VPFVGSignal_vf_atr > 0"                 # Valid ATR calculation

  # LONG EXIT CONDITIONS
  exit_long:
    - "VPFVGSignal_vf_long == False"           # Confluence signal ends
    - "RiskManagement_exit_long_risk"         # Risk management exit (stop/target hit)

  # SHORT ENTRY CONDITIONS - Simplified and more permissive  
  entry_short:
    - "VPFVGSignal_vf_short"                   # Primary confluence signal
    - "VPFVGSignal_vf_atr > 0"                 # Valid ATR calculation

  # SHORT EXIT CONDITIONS
  exit_short:
    - "VPFVGSignal_vf_short == False"          # Confluence signal ends  
    - "RiskManagement_exit_short_risk"        # Risk management exit (stop/target hit)

# Extended backtesting for comprehensive market condition testing
backtest:
  cash: 100000          # Initial capital
  commission: 0.0002    # 0.04% commission per trade (realistic for spot)
  from: "2024-01-01"    # Start date
  to: "2025-01-01"      # End date

# Equity Protection - Prevent catastrophic drawdowns
equity_protection:
  enabled: false
  drawdown_threshold: 0.25              # 25% first-loss stop
  enable_on_bias_flip: true             # Re-enable trading on bias flip
  smoothing_window: 5                   # 5-period smoothing
  min_equity_history: 10                # Minimum history before protection activates
  flatten_positions_on_trigger: true    # Flatten positions when protection triggers
  disable_new_entries: true             # Disable new entries when protection active

# Risk Management - Risk-per-trade position sizing
risk_management:
  enabled: true
  risk_pct: 0.02                       # Increase to 2% risk per trade (was 0.05 which was too aggressive)
  max_position_pct: 0.3                # Increase maximum to 30% of equity per position
  use_position_sizing: true             # Enable risk-based position sizing

# Optimization parameters (disabled for now)
optimization:
  parameters:
    # VP-FVG Confluence Signal parameters
    - name: "VPFVGSignal.lvn_dist_multiplier"
      type: "float"
      low: 0.1
      high: 0.5
      default: 0.25
      step: 0.05
      description: "LVN distance multiplier"
    - name: "VPFVGSignal.poc_shift_multiplier"
      type: "float"
      low: 0.3
      high: 0.8
      default: 0.5
      step: 0.1
      description: "POC shift multiplier"
    - name: "VPFVGSignal.hvn_overlap_pct"
      type: "float"
      low: 0.5
      high: 0.9
      default: 0.7
      step: 0.1
      description: "HVN overlap percentage"

  # Default optimization settings
  defaults:
    method: "bayesian"
    validation: "walk_forward"
    metric: "sharpe_ratio"
    max_iterations: 50